### ISSUE TITLE
GPL-928 Housekeeping - LH - Reflected server-side cross-site scripting (S)

### ISSUE THREAD

**Issue by emrojo** [sanger/lighthouse#287]
**Describe the Housekeeping**
New security code check are adding a warning to every pull request created because of previous version of code not passing the new security validation checks in this repo. There are 3 alerts https://github.com/sanger/lighthouse/security/code-scanning?query=ref%3Arefs%2Fpull%2F286%2Fmerge

Part of Code QL
Eg code [here](https://github.com/sanger/lighthouse/pull/286/files)

They need to be solved to pass correctly all the tests for the pull request. The message we get about this problems is:

Reflected server-side cross-site scripting

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by harrietc52** [comment]
Trying to recreate alert in linked PR but I think it only picks up new alerts, and as it was dismissed in [this PR](https://github.com/sanger/lighthouse/pull/286/files) need to work out how to trigger it again

**Comment by harrietc52** [comment]
Looked into this and failed to recreate issue. 
Assumptions are that the alert was a false positive, possibly caused from a bug in the GitHub action or a dependency has been updated in the meantime.
As the warning was on code that hadn't been changed nor hasn't changed since, closing this for now as there are no current warnings.
